### PR TITLE
Move COMPONENT_CONTROL enum and MAV_CMD_COMPONENT_CONTROL to the 'development' dialect

### PR DESCRIPTION
**Pull request by TSC21**
This will make it easier to upstream the feature. Follows with an update in the mavlink headers in PX4, MAVSDK and AMC.

### CODE REVIEW

**Review by julianoes — COMMENTED** [review]
Changes to development.xml need to come via upstream, right?

**Comment by TSC21** [comment]
> Changes to development.xml need to come via upstream, right?

Why? Does it matter? I am actually doing the other way around so I can then upstream

**Comment by julianoes** [comment]
@TSC21 I guess that works too. So we don't require auterion.xml at all?

**Comment by TSC21** [comment]
> @TSC21 I guess that works too. So we don't require auterion.xml at all?

We do if there are specifics that don't make sense to usptream or cannot to be upstreamed at all, which would be quite rare but we still have this as a "safe" place to add them. I would propose that all that is to be upstreamed we add it directly to "development.xml", implement something  that is visible in any of the Mavlink dependent repos, and then issue the PR with a reference to the working implementation.

**Review by julianoes — APPROVED** [review]

**Pull request merged**
